export const SALDOS_CONTABLES_QUERY = `
   SELECT DATE(SC.FECHA) as fecha, DD.NOMBREOFICINA as nombreOficina, DD.CODIGOOFICINA as codigoOficina,
           D.CODIGO as codigoCuentaContable, D.NOMBRE as nombreCuentaContable, CC.ESDEUDORA as esDeudora,
           IF(CC.ESDEUDORA = 1, SC.SALDOINICIAL + SC.TOTALDEBITO - SC.TOTALCREDITO,
              -1 * (SC.SALDOINICIAL + SC.TOTALDEBITO - SC.TOTALCREDITO)) as saldo
    FROM \`FBS_CONTABILIDADES.SALDOCONTABLE\` SC
             INNER JOIN
        (
            SELECT CC.SECUENCIALDIVISION, CC.ESDEUDORA FROM
                \`FBS_CONTABILIDADES.CUENTACONTABLE\` CC
            WHERE CC.ESTAACTIVA = 1) CC
        ON CC.SECUENCIALDIVISION = SC.SECUENCIALCUENTACONTABLE
             INNER JOIN \`FBS_GENERALES.DIVISION\` D ON D.SECUENCIAL = CC.SECUENCIALDIVISION
             INNER JOIN
        (
            SELECT D.SECUENCIAL SECUENCIALOFICINA, D.CODIGO CODIGOOFICINA, D.NOMBRE NOMBREOFICINA FROM
                \`FBS_GENERALES.DIVISION\` D
            INNER JOIN \`FBS_GENERALES.NIVELDIVISION\` ND ON ND.SECUENCIAL = D.SECUENCIALNIVEL
            INNER JOIN \`FBS_GENERALES.TIPODIVISION\` T ON T.SECUENCIAL = ND.SECUENCIALTIPODIVISION
    WHERE T.SECUENCIAL = 34
        ) DD ON DD.SECUENCIALOFICINA = SC.SECUENCIALDIVISIONORGANIZACION
    WHERE SC.FECHA = :fecha
`;

export const COUNT_SALDOS_CONTABLES_QUERY = `
    SELECT COUNT(*) as totalSaldosContables
    FROM \`FBS_CONTABILIDADES.SALDOCONTABLE\` SC
    INNER JOIN \`FBS_CONTABILIDADES.CUENTACONTABLE\` CC 
        ON CC.SECUENCIALDIVISION = SC.SECUENCIALCUENTACONTABLE
        AND CC.ESTAACTIVA = 1
    INNER JOIN \`FBS_GENERALES.DIVISION\` D 
        ON D.SECUENCIAL = CC.SECUENCIALDIVISION
    INNER JOIN \`FBS_GENERALES.DIVISION\` DD 
        ON DD.SECUENCIAL = SC.SECUENCIALDIVISIONORGANIZACION
    INNER JOIN \`FBS_GENERALES.NIVELDIVISION\` ND 
        ON ND.SECUENCIAL = DD.SECUENCIALNIVEL
    INNER JOIN \`FBS_GENERALES.TIPODIVISION\` T 
        ON T.SECUENCIAL = ND.SECUENCIALTIPODIVISION
        AND T.SECUENCIAL = 34
    WHERE SC.FECHA BETWEEN :fechaInicio AND CURRENT_DATE()
`;

export const ULTIMA_FECHA_AWS_QUERY = `
    SELECT MAX(DATE(FECHA)) as ultimaFechaConSaldos
    FROM \`FBS_CONTABILIDADES.SALDOCONTABLE\`
    WHERE FECHA IS NOT NULL
    AND FECHA BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 365 DAY) AND CURRENT_DATE()
`;